### ISSUE TITLE
Linkage between data & frontend

### ISSUE THREAD

**Issue by nishi7409** [nishi7409/HASSPathways#10]
At this point, we should have the frontend working off real data (file_name.json) rather than dummy data!

**Comment by nishi7409** [comment]
real data - https://github.com/nishi7409/HASSPathways/tree/master/JSON%20files
@Vincentqchen

**Comment by nishi7409** [comment]
![image](https://user-images.githubusercontent.com/20250366/112794770-10b0bb80-9085-11eb-9472-7bec2851addc.png)
The bottom portion gets covered by the "We love feedback" part

Can you look into fixing that?

**Comment by Vincentqchen** [comment]
1. Need to look into importing the course category data (CI, HI, etc.)
2. Also need to make sure if a student picks one course, they can't pick that same course again

**Comment by amontes261** [comment]
@nishi7409 I took care of the bottom portion getting covered by the "We love feedback" part in 09fd249142b75e9653497c6c9eeb8212f6154b54 about a week or two ago. My bad, didn't know Vin was assigned this before I did it.
