### ISSUE TITLE
Third Course Selection & Notification

### ISSUE THREAD

**Issue by nishi7409** [nishi7409/HASSPathways#23]
After you've made your third course selection, there should be some form of a notification on the screen that states that all three courses have been selected.

You could implement something found here:
https://maronato.github.io/vue-toastification/ or https://www.npmjs.com/package/vue-notification

Additionally, when the notification is present, the courses progress bar should reset sending the user back to the first course selection panel.
![image](https://user-images.githubusercontent.com/20250366/105622211-7ab6a580-5e35-11eb-81e1-fdd4fcab8644.png)

**This should not mess up saving this data to the `My Pathways` page!**

**Comment by Vincentqchen** [comment]
Reiterated version - Confirmation button called 'save'. When clicked will send a confirmation notification and send the user back to the first panel.
